### ISSUE TITLE
Have you looked at wallymathieu/with?

### ISSUE THREAD

**Issue by wallymathieu** [ehorrent/With.Extensions#1]
I've done something similar in:
https://github.com/wallymathieu/with

Any thoughts?

**Comment by ehorrent** [comment]
Didn't see your repository on immutables, great work !
My next objective is to make instance creation as fast as possible, without calling Invoke (by using compiled expressions).

**Comment by wallymathieu** [comment]
Sounds fun! Good luck! :)

**Comment by wallymathieu** [comment]
Noticed that there was quite the penalty of using expression and invoke to pull out values for: https://github.com/wallymathieu/with#performance-impact-of-working-with-immutable-types-by-using-with-in-c-for-version 
I guess you have the same issue
